first draft of joystick messages
Auterion/mavlink pull request #114
Opened 2022-04-11 15:13 UTC by baumanta

very first draft for the mavlink messages we need for assigning functionalities to a mavlink joystick. Opening PR as first point of discussion

https://auterion.atlassian.net/wiki/spaces/GI/pages/2385903617/Dynamic+Button+and+Axis+assignment+for+Gipfeli

2022-04-11 20:06 UTC, JonasVautherin requested changes
Just a wrong description and a nitpick. Otherwise I think it looks good, we should start trying it :+1:

2022-04-11 20:06 UTC, JonasVautherin commented on message_definitions/v1.0/minimal.xml
> +        <description>Winch</description>
```suggestion
        <description>Joystick</description>
```

2022-04-11 20:06 UTC, JonasVautherin commented on message_definitions/v1.0/auterion.xml
> +      <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
Same here for wip

2022-04-11 20:06 UTC, JonasVautherin commented on message_definitions/v1.0/auterion.xml
> +      <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
Not sure if we should use that, I think I heard at some point that we were going away from it.

We will merge it in our dialect, possibly change it, and the day it gets upstream it will have to be ready and stable. So there is no need to say that it is unstable.

Not completely sure, though, but that would be my opinion :see_no_evil:

2022-04-12 07:52 UTC, baumanta commented on message_definitions/v1.0/auterion.xml
> +      <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
@DanielePettenuzzo told me to put that wip, even if we use it in our own dialect. Because merging it now seems to be the easiest way to test it, because it is a nightmare to manually build it. So his suggestion was to merge it (now) in wip state and remove the wip once we are sure it is how we want it. Does that make sense?

2022-04-12 09:25 UTC, JonasVautherin commented on message_definitions/v1.0/auterion.xml
> +      <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
Ok, if that's needed internally, let's keep it :+1:. Anyway it doesn't do anything :grin:

2022-04-12 09:25 UTC, JonasVautherin approved these changes

2022-04-13 15:52 UTC, merged

2022-04-14 05:59 UTC, bkueng commented on message_definitions/v1.0/auterion.xml
> +      <field type="char[140]" name="joy_definition_uri">Joystick definition URI (if any, otherwise only basic functions will be available). HTTP- (http://) and MAVLink FTP- (mavlinkftp://) formatted
MAVLink switched to json, and it looks like this should be using https://mavlink.io/en/services/component_information.htmlhttps://mavlink.io/en/services/component_information.html

2022-04-14 07:23 UTC, JonasVautherin commented on message_definitions/v1.0/auterion.xml
> +      <field type="char[140]" name="joy_definition_uri">Joystick definition URI (if any, otherwise only basic functions will be available). HTTP- (http://) and MAVLink FTP- (mavlinkftp://) formatted
Good to know, thanks @bkueng! We'll go this way then :+1: