auterion: enable CMD_DO_SET_SLOW_SPEED
Auterion/mavlink pull request #167
Opened 2022-11-29 09:41 UTC by cmic0

Initial prototype to get the slow speed mode working

2022-11-29 10:16 UTC, TSC21 commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable slow speed mode and set its constraints.</description>
Can we please clarify the usage of this message and why this vs the MAV_CMD_DO_CHANGE_SPEED? This message also seems to imply that we are dependent on the autopilot status and parameters, but doesn't clarify what exactly those are.

I know this is being added to the Auterion dialect, but if we want to eventually PX4 to upstream, this needs to be standardized in common (initially in development for sure). And as it is right now I can 100% guarantee this will not pass in an upstream mavlink review.

2022-11-29 10:50 UTC, tstastny requested changes

2022-11-29 10:50 UTC, tstastny commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable slow speed mode and set its constraints.</description>
@TSC21 the intention for the moment is not to have something upstream passable. we are prototyping to gain experience. this will change likely quite fast and often in the coming weeks. -- it will be revised in patch release before advertising to all customers as well.

2022-11-29 10:50 UTC, tstastny commented on message_definitions/v1.0/auterion.xml
> +        <wip/>
```suggestion
        <wip/>
        <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
```

2022-11-29 21:51 UTC, hamishwillee commented on message_definitions/v1.0/auterion.xml
> +        <param index="2">Empty.</param>
Typically these are done in common.xml as "Reserved "
```suggestion
        <param index="2">Reserved (set to 0)/param>
```

The "set to 0"  means that the do nothing command on this param MUST be zero - otherwise if you update the field to be used for something else, there will be side effects of having a valid "0" value. For example, you cannot easily make this param be a temperature range from -20 to 20 as "0" would be a valid value.

So if you think you might need to this to set values where 0 is valid you might instead do:

```
<param index="3" reserved="true" default="NaN">Reserved (set to NaN)</param>
```

Recommend using at least one of these in the set on some value other than param 5 or 6.

2022-11-29 21:52 UTC, hamishwillee commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable speed limits and set constraints.</description>
What's the use case. What limits? What constraints? I wouldn't accept this in common.xml because it is so broad as to be meaningless.

2022-11-29 21:58 UTC, TSC21 commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable slow speed mode and set its constraints.</description>
@tstastny fair. But you still haven't answered any of my questions above.

2022-11-29 23:06 UTC, cmic0 commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable speed limits and set constraints.</description>
@hamishwillee we are prototyping a "slow speed" position flight mode, where the max velocity limits of the vehicle are temporarily changed based on external conditions. The initial use case is to scale down vehicle's yaw rate based on zoom level coming from a camera, this is a fundamental feature required when doing inspections with UAVs. The future expansions can also be to use the same command to limit horizontal velocities when flying in position ("tripod" mode), in Europe for example such limitations are required by regulation entities when flying close to group of people.

2022-11-29 23:11 UTC, cmic0 commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable slow speed mode and set its constraints.</description>
Do change speed changes the setpoint, in this case we want to change the limits. It is not a flightmode because you could also argue that this is the same position flight mode (which already exists) just with some temporary constraints

2022-12-01 05:15 UTC, hamishwillee commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable speed limits and set constraints.</description>
Shouldn't those constraints be in the command? Otherwise how will the system know what constraints you are talking about and what values to use. So if this is about speed only, you would put max/min speed as params. If it is more general, what other things might you constrain?

 Scenario, later on you decide that you want to have another set of constraints that are gated on people being underneath - how are you representing the different from the first set?

Normally transient constraints have a default lifetime of the next mode change. So if you went into mission from position mode, these constraints would be cleared.

I think you'd be best off getting broader feedback too if you want this upstream. Of course you don't have to, but then no one has to accept this upstream either.

2022-12-01 08:32 UTC, cmic0 commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable speed limits and set constraints.</description>
Thanks @hamishwillee for the feedback, yep the plan is to add max limits as parameters later on but we are still exploring a more basic functionality. In regard opening a PR upstream for broader discussion we'll do it soon, we're currently sprinting to meet a deadline

2022-12-01 08:50 UTC, hamishwillee commented on message_definitions/v1.0/auterion.xml
> +        <description>Enable/Disable speed limits and set constraints.</description>
Good luck @cmic0 - I'm glad I don't have your product deadlines!

2022-12-07 10:18 UTC, merged