APX4-3139 - Add VELOCITY_LIMITS msg
Auterion/mavlink pull request #206
Opened 2023-06-16 14:26 UTC by marcinolokk

[jira](https://auterion.atlassian.net/browse/APX4-3139?atlOrigin=eyJpIjoiODVkYzg2YmFjZGUwNDU1OGJiNjA4NmM0ZjZhZDdlMDciLCJwIjoiaiJ9)
This pr is part of a bigger scope which aims to enable "slow mode" on a vehicle. 
The velocity_limits message consists of: 

 * horizontal velocity limit
 * vertical velocity limit 
 * yaw rate limit
 * ~Bitmask that describes which one of the above is enabled/disabled~
 * ~Timeout after which the velocity setpoint won't be considered anymore~

2023-06-28 08:31 UTC, tstastny requested changes
Thanks for pushing on this @marcinolokk 

A couple things:
1. These are not "setpoints" - they are **limits**.
2. I thought we had already discussed that a timeout does not make sense to dictate in the message. The receiver can determine how they want to handle this on their own.

On the fields - please make sure not to call them setpoints, and we may also need to add more specificity in what frame they are considering. E.g. what does "horizontal speed" mean? Is it in XY body frame? (I presume we actually want NE local inertial frame)

2023-06-28 08:59 UTC, MaEtUgR requested changes
These are my suggestions. I'm happy to discuss.

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +    <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
```suggestion
    <wip/>
    <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
```

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +    <!-- This message is work-in-progress and it can therefore change. It should NOT be used in stable production environments. -->
This tag is what actually makes the message work in progress for the (documentation) system parsing.

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +      <description>Setpoint of horizontal speed, vertical speed and yaw rate.</description>
```suggestion
      <description>Temporary limits for horizontal speed, vertical speed and yaw rate to slow down the vehicle from the default configuration during operation. This message should be streamed at 1Hz while the lower limits apply. The consumer implements a timeout and returns to default limits in case the stream is lost. Accelerations are automatically adjusted accordingly.</description>
```

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="horizontal_speed" units="m/s">Horizontal speed in m/s</field>
```suggestion
      <field type="float" name="horizontal_speed" units="m/s">Limit for horizontal movement in local inertial north east frame. NaN: Use vehicle default speed.</field>
```

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="vertical_speed" units="m/s">Vertical speed in m/s</field>
```suggestion
      <field type="float" name="vertical_speed" units="m/s">Limit for vertical movement in local inertial down frame. NaN: Use vehicle default speed.</field>
```

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="yaw_rate" units="rad/s">Yaw rate in rad/s</field>
```suggestion
      <field type="float" name="yaw_rate" units="rad/s">Limit for vehicle turn rate around its yaw axis. NaN: Use vehicle default rate.</field>
```

2023-06-28 08:59 UTC, MaEtUgR commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="type_mask" enum="VELOCITY_LIMITS_MASK" display="bitmask">Bitmap to indicate which velocity setpoint should be considered.</field>
```suggestion
```

2023-06-28 09:01 UTC, MaEtUgR commented
Now it seems a different base is used and unrelated changes got into the diff 👀

2023-06-28 11:27 UTC, MaEtUgR reviewed
Nice, thanks for addressing!
The separate north east and down frame description I suggested is not very coherent with the rest of MAVLink. What about we reference the existing frame description `MAV_FRAME`. The `LOCAL` frame fits the horizontal and vertical velocity independently of offset because it's a velocity and independently of NED/ENU because we specify horizontal and vertical. That would make it clear, no?
https://github.com/mavlink/mavlink/blob/2020d316014a96419ad96012a936eef5fa43efcf/message_definitions/v1.0/common.xml#L238

Other than that I think it's good.

2023-07-03 09:17 UTC, marcinolokk commented
As discussed with @MaEtUgR this work has been moved to the [upstream](https://github.com/mavlink/mavlink/pull/2015).

2023-09-21 12:05 UTC, TSC21 commented
This is already in and in the `development`.

2023-09-21 12:05 UTC, closed without merging